### ISSUE TITLE
Bring over #11 from legacy `sharkiq`

### ISSUE THREAD

**Issue by funkybunch** [JeffResc/sharkiq#2]
@TheLastFrame has a PR that adds EU app support on the legacy repo https://github.com/ajmarks/sharkiq/pull/11

This issue is being created to track migrating this PR over to the new repo.

**Comment by TheLastFrame** [comment]
Opened now a PR for this #16

**Comment by funkybunch** [comment]
Closed via #16

**Comment by funkybunch** [comment]
Closed via #16
