### ISSUE TITLE
Help: How to install?

### ISSUE THREAD

**Issue by proactivematter** [JeffResc/sharkiq#20]
Hey all,

Not a dev, just a tinkerer. I run Home Assistant via HyperV and I was using the old SharkIQ integration until it stopped working. Not sure how to get this one installed with my VM setup. Would someone care to provide some guidance?

Many thanks.

**Comment by funkybunch** [comment]
Hey there @proactivematter,

This integration is now the canonical integration built into Home Assistant (as of recently).

If you're running Home Assistant core version 2022.4 or later, this will be the fork used when you install the SharkIQ integration.

If you're running the most recent version and it still isn't working could you try/check a couple things for me?
1. Reload the integration and see if it starts working again.  There is a known issue with token expiration that carried over from the previous plug-in maintainer that we haven't had a chance to resolve yet.
2. If you are in the EU, there are different API endpoints that need to be used.  While we have merged Code to add this support to the Python plug-in, we have not updated the code on the Home Assistant side to configure it yet.
3. If your Core instance is up to date, and neither of those apply to you, please post the errors you are getting in the logs to this thread so we can take a look.

All three maintainers of this plug-in are undergrad or graduate students and it is finals week (at least for me), so we will look at any further issues as soon as possible, but it may not be as timely as normal for us.

Many thanks!

**Comment by proactivematter** [comment]
That was it! My Home Assistant was stuck in 2022.2 and couldn't be updated for some reason. I had to revert the VM to a previous backup, after which I was able to update it, and after the updating the integration was working immediately.

Thank you so much for the detailed response and thank you for bringing this integration back to working condition. You guys are awesome.
