### ISSUE TITLE
not getting vac list

### ISSUE THREAD

**Issue by emann3** [JeffResc/sharkiq#31]
It has been a month since I used this, but back at it now and I am not getting anything back from ayla_api.get_devices().  its empty.

I have 2 vacs and I used to get them both.  anyone else seeing issues?

I seem to sign-in ok (if I change the password to an invalid value, I get an error earlier).

**Comment by funkybunch** [comment]
I'm not near my computer right now so I can't test directly, but I think I remember seeing somewhere that Ayla had deprecated the synchronous functions in favor of the async equivalents.

Could you try the async version and see if that works?  If it does then it might be time to remove them from this library.  We've long been exclusively using the async functions in Home Assistant so we didn't take the time to write tests for the synchronous functions when we formed the repo.
