### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by JeffResc** [JeffResc/sharkiq#4]
Tests should be added to the project to ensure each PR does not introduce breaking changes.

I am currently working on this in the [add-tests](https://github.com/JeffResc/sharkiq/tree/add-tests) branch and will open a PR when they are ready.

**Comment by JeffResc** [comment]
This is proving harder than expected, as the [synchronous](https://github.com/JeffResc/sharkiq/blob/main/README.md#simple-operation) methods don't implement web sessions.

Is it worth maintaining these synchronous methods? I believe it's easy enough to run it asynchronously when implementing this module, but I'd like to get some input. If we remove the synchronous methods, we'd also be able to remove the `requests` module dependency as well.

I do not believe Home Assistant utilizes the synchronous methods at all, so nothing would break in terms of that.

@funkybunch @AritroSaha10 Thoughts?

**Comment by AritroSaha10** [comment]
I agree that the synchronous functions aren't completely useful considering the simplicity of the async methods. In addition, I doubt that they are used much, if it all, since most repos that are reported to use the library are just forks of HA core. Maybe we can keep a legacy fork in case if anyone is interested in using them?

**Comment by JeffResc** [comment]
> I agree that the synchronous functions aren't completely useful considering the simplicity of the async methods. In addition, I doubt that they are used much, if it all, since most repos that are reported to use the library are just forks of HA core. Maybe we can keep a legacy fork in case if anyone is interested in using them?

There's also quite a few ways to call synchronous functions from asynchronous functions, but in my small amount of testing, I wasn't able to get it working. This would streamline things having the synchronous and asynchronous functions call essentially the exact same code.

**Comment by travipross** [comment]
I've begun work on this issue in #9. So far I've set up a number of basic unit tests with a typical `pytest` structure, which could be a good starting point for further tests to be added down the road.
