### ISSUE TITLE
Refresh Authentication Token

### ISSUE THREAD

**Issue by funkybunch** [JeffResc/sharkiq#5]
The legacy code seems to support auth token refreshing but there is no usage of the method used to actually do the token refresh.  As a result, the integration becomes unavailable after the original auth token expires.

See https://github.com/JeffResc/sharkiq/blob/4136e64ff3ddfa20a576909a482ecc45bcbfd044/sharkiq/ayla_api.py#L99

**Comment by funkybunch** [comment]
@JeffResc @AritroSaha10 have you had the daily disconnecting bug happen with this integration?  It seems there is code that establishes the ability to refresh the auth token, but it isn't used anywhere else in the code.

Did I miss something or is the function really not used?

**Comment by AritroSaha10** [comment]
> have you had the daily disconnecting bug happen with this integration? 
I have had this happen to me a lot about a month ago, but it seems to have fixed itself.

**Comment by JeffResc** [comment]
Is this the same error you've been seeing? I've still been getting this:
![image](https://user-images.githubusercontent.com/5752328/161389561-e74c0adc-008f-46bc-ae6b-4ff331ec33e6.png)

**Comment by funkybunch** [comment]
Yup, that's it.  There was another discussion on the legacy repo on a PR that seemed to suggest fixing it but it was just a URL change which isn't going to solve the token refresh issue.

**Comment by AkaMrBill** [comment]
I have created a Node-Red script that looks at the Shark Integration Identity ID once a minute, If it returns "unavailable", it then triggers an API call to reload. This has worked flawlessly up until a couple weeks ago. Now even this fails to make the vacuums appear. Thus my automations now fail to run. The Shark(s) are always "unavailable".

**Comment by funkybunch** [comment]
> Now even this fails to make the vacuums appear. Thus my automations now fail to run. The Shark(s) are always "unavailable".

The reason they're unavailable now is SharkIQ changed the API endpoint.  A PR has already been merged to the Home Assistant repo to fix that.  Once it is merged in your NodeRed automation will work again.

I have a similar automation in my instance, but it's a hacky workaround hence this issue to build in token refreshes.

**Comment by AkaMrBill** [comment]
Excellent,  thanks for the update.

BTW, is there a way I can edit my current "script" to allow it to work?
Just curious.

BK

**Comment by JeffResc** [comment]
Hi @AkaMrBill. The change to fix the Shark integration has been accepted into Home Assistant, but is not yet available in the `stable` release. I believe it should be added, next Wednesday, but that up to the Home Assistant development team. In the meantime, if you'd like access to the fix, you can update to the beta version of Home Assistant Core, but I'd advise you to take a backup before the update as the beta branch is not guaranteed to be stable.

**Comment by funkybunch** [comment]
@AkaMrBill the updated API endpoint is included in the 2022.4 release that is out now.  Update to this version and your NodeRed automation should start working again.

Unfortunately the 2022.4 release doesn't solve the need to have the reload automation.

**Comment by AkaMrBill** [comment]
@funkybunch   Hi Mark, I just opened an issue on this as my "Reload Automation" has been failing for a couple months now. I need to manually disable and re-enable the integration to make it work.
So, any suggestions on how to set up "Reload Automation"?

**Comment by funkybunch** [comment]
@AkaMrBill sorry just saw you also posted here.  Check that your `entry_id` is still the same.  Mine changed during the last major Home Assistant update and I had to setup my automation again.  Seems like you do have a reload automation already so you probably don't need this, but for other folks who might find it useful, here is an example reload automation as promised in the other thread.

```
alias: Watcher - Shark Availability
description: ''
trigger:
  - platform: state
    entity_id: vacuum.shark
    for:
      hours: 0
      minutes: 2
      seconds: 0
    to: unavailable
condition: []
action:
  - service: homeassistant.reload_config_entry
    data:
      entry_id: <SOME_HASH_STRING>
mode: single
```

Put in the `entity_id` of your vacuum under the trigger, and the `entry_id` of your integration under the action data.  You can get the entry id by opening up dev tools to the network tab and navigating to your devices & services page where it lists out all of your integrations.  Click the context menu for the SharkIQ integration (with dev tools still open to the network tab) and click "Reload".  The XHR request that shows up in dev tools should look something like this:
```
<YOUR_HASS_URL>/api/config/config_entries/entry/<SOME_HASH_STRING>/reload
```

That `SOME_HASH_STRING` is your `entry_id`.

**Comment by AkaMrBill** [comment]
@funkybunch ,
Thanks! This indeed did resolve my issue. I will close out the issue I raised.

BK

**Comment by funkybunch** [comment]
Closing this issue as it is already supported in this library and resolved in a PR on the HA repo.
